version: '3'
services:
  db:
    image: postgres
    volumes:
      - espertofit_payments_hdd:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 6000 -b '0.0.0.0'"
    volumes:
      - .:/espertofit
    ports:
      - "82:6000"
    depends_on:
      - db
      - redis
  redis:
    image: redis
    command: redis-server
    container_name: redis
    ports:
     - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data

volumes:
  espertofit_payments_hdd:
  redis:

networks:
  default:
    external:
      name: esperto-network
